name: Test

on:
  push:
    branches-ignore: [main, release/**]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash .ci/runChecks.sh

  test-loki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Backbone
        uses: nmshd/start-backbone@latest
        with:
          consumerapi-version: v4.2.0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build:schemas
      - run: npm run test:ci:lokijs
        env:
          NMSHD_TEST_BASEURL: http://localhost:5000
          NMSHD_TEST_CLIENTID: test
          NMSHD_TEST_CLIENTSECRET: test

  test-mongo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Backbone
        uses: nmshd/start-backbone@latest
        with:
          consumerapi-version: v4.2.0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: supercharge/mongodb-github-action@v1.9.0
      - run: npm ci
      - run: npm run build:schemas
      - run: npm run test:ci:mongodb
        env:
          NMSHD_TEST_BASEURL: http://localhost:5000
          NMSHD_TEST_CLIENTID: test
          NMSHD_TEST_CLIENTSECRET: test

  test-ferret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Backbone
        uses: nmshd/start-backbone@latest
        with:
          consumerapi-version: v4.2.0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: js-soft/ferretdb-github-action@1.1.0
        with:
          ferretdb-telemetry: "enabled"
          ferretdb-version: latest
      - run: npm ci
      - run: npm run build:schemas
      - run: npm run test:ci:ferretdb
        env:
          NMSHD_TEST_BASEURL: http://localhost:5000
          NMSHD_TEST_CLIENTID: test
          NMSHD_TEST_CLIENTSECRET: test
