name: Test

on:
  push:
    branches-ignore: [main, release/**]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash .ci/runChecks.sh

  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Backbone
        uses: nmshd/start-backbone@latest
        with:
          consumerapi-version: v4.2.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
      - run: npm run test:node:mongodb
        env:
          CONNECTION_STRING: mongodb://127.0.0.1:27017
          NMSHD_TEST_BASEURL: http://localhost:5000
          NMSHD_TEST_CLIENTID: test
          NMSHD_TEST_CLIENTSECRET: test

  test-node-ferret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Backbone
        uses: nmshd/start-backbone@latest
        with:
          consumerapi-version: v4.2.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - uses: js-soft/ferretdb-github-action@1.0.2
        with:
          ferretdb-telemetry: "enabled"
      - run: npm run test:node:mongodb
        env:
          CONNECTION_STRING: mongodb://127.0.0.1:27017
          NMSHD_TEST_BASEURL: http://localhost:5000
          NMSHD_TEST_CLIENTID: test
          NMSHD_TEST_CLIENTSECRET: test

  test-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Backbone
        uses: nmshd/start-backbone@latest
        with:
          consumerapi-version: v4.2.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: browser-actions/setup-chrome@latest
      - run: npm ci
      - run: npm run build:ci
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          COMMIT_HASH: ${{ github.sha }}
      - run: npm run test:web:min
        env:
          NMSHD_TEST_BASEURL: http://localhost:5000
          NMSHD_TEST_CLIENTID: test
          NMSHD_TEST_CLIENTSECRET: test
